name: cluemaster-mediadisplay # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.4.7.17' # just for humans, typically '1.2+git' or '1.3.2'
summary: Clumaster.io Media Display for Escape Rooms # 79 char long summary
description: |
  ClueMaster Media Display is a Dynamic TV Display software for escape rooms.
  It shows escape room countdown timers, visual text messages, video, audio,
  and photo clues.

grade: stable # must be 'stable' to release into candidate/stable channels / devel
confinement: strict # use 'strict' once you have the right plugs and slots /devmode

architectures:
    - build-on: amd64

apps:
  cluemaster-mediadisplay:
    command: bin/desktop-launch $SNAP/cluemaster_display
    plugs:
      - home
      - desktop-legacy
      - desktop
      - wayland
      - x11
      - unity7
      - network
      - opengl
      - gsettings
      - pulseaudio
      - network-bind
      - screen-inhibit-control

parts:
  cluemaster-mediadisplay:
    after: [desktop-qt5]
    plugin: dump
    source: https://github.com/ClueMaster-LLC/MediaDisplay-MPV.git
    source-subdir: binaries
    stage-packages:
      - libcanberra-gtk0
      - libdrm2
      - mesa-vdpau-drivers
      - libmpv-dev
      - libmpv1
      - freeglut3
      - libglu1-mesa
      - vdpau-driver-all
      - libdrm-amdgpu1
      - va-driver-all
      - autoconf
      - libtool
      - libdrm-dev
      - xorg
      - xorg-dev
      - openbox
      - libx11-dev
      - libgl1-mesa-glx
      - libgl1-mesa-dev
      - mesa-va-drivers
      - intel-media-va-driver
      - libva-dev

  custom-code:
    after: [cluemaster-mediadisplay]
    plugin: nil
    override-build: |
      echo "Setting gtk path ..."
      export GTK_PATH=$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0
      echo "Unsetting session manager"
      unset SESSION_MANAGER
      echo "Custom commands successful ..."


  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
