name: cluemaster-mediadisplay-core 
base: core20 
version: '1.0.20'
summary: Clumaster.io Media Display for Escape Rooms 
description: |
  ClueMaster Media Display is a Dynamic TV Display software for escape rooms.
  It shows escape room countdown timers, visual text messages, video, audio,
  and photo clues.

grade: stable 
confinement: strict 

apps:
  cluemaster-mediadisplay-core:
    daemon: simple
    restart-condition: always
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch $SNAP/bin/desktop-launch $SNAP/bin/prepare-launch $SNAP/cluemaster_display
    environment:
      DISABLE_WAYLAND: 1

  pulseaudio:
    command: bin/pulseaudio
    daemon: simple
    install-mode: disable

  pactl:
    command-chain: [bin/client-wrapper]
    command: usr/bin/pactl

  paplay:
    command-chain: [bin/client-wrapper]
    command: usr/bin/paplay

  parec:
    command-chain: [bin/client-wrapper]
    command: usr/bin/parec

  config:
    command: bin/config


plugs:
  playback:
    interface: audio-playback
  record:
    interface: audio-record
  home:
  wayland:
  x11:
  network:
  opengl:
  network-bind:
  shutdown:
  process-control:
  network-control:
  hardware-observe:
  alsa:
  bluez:

slots:
  audio-playback:
  audio-record:

parts:
  copy-source-code:
    after: [desktop-qt5]
    plugin: dump
    source: cluemaster_display/
    stage-packages:
      - ffmpeg
      - libass9
      - mpv
      - alsa-base
      - locales
      - libvdpau1
      - i965-va-driver
      - libmpv1
      - va-driver-all
      - vdpau-driver-all
      - mesa-va-drivers
      - libvdpau-va-gl1
      - libglu1-mesa
      - samba-libs
      - git
      - python3-dbus
      - qtwayland5
      - mesa-utils
      - libgl1-mesa-dri
      - python3-pyqt5.qtmultimedia
      - libqt5multimedia5-plugins

    stage:
      - -usr/share/alsa/alsa.conf
      - -usr/share/alsa/cards/HDA-Intel.conf
      - -usr/share/alsa/cards/USB-Audio.conf
      - -usr/share/alsa/cards/aliases.conf
      - -usr/share/alsa/pcm/center_lfe.conf
      - -usr/share/alsa/pcm/default.conf
      - -usr/share/alsa/pcm/dmix.conf
      - -usr/share/alsa/pcm/dsnoop.conf
      - -usr/share/alsa/pcm/front.conf
      - -usr/share/alsa/pcm/hdmi.conf
      - -usr/share/alsa/pcm/iec958.conf
      - -usr/share/alsa/pcm/modem.conf
      - -usr/share/alsa/pcm/rear.conf
      - -usr/share/alsa/pcm/side.conf
      - -usr/share/alsa/pcm/surround21.conf
      - -usr/share/alsa/pcm/surround40.conf
      - -usr/share/alsa/pcm/surround41.conf
      - -usr/share/alsa/pcm/surround50.conf
      - -usr/share/alsa/pcm/surround51.conf
      - -usr/share/alsa/pcm/surround71.conf
      - -README.md


    stage-snaps: [mir-kiosk-x11]

  extras:
    plugin: dump
    source: static/
    organize:
      "prepare-launch": "bin/"

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 
      - try: [appmenu-qt5]
      - locales-all
      - xdg-user-dirs
      - libdrm2
      - libgbm1
      - fcitx-frontend-qt5

    stage:
      - -usr/lib/x86_64-linux-gnu/dri/d3d12_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/i915_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/i965_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/iris_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/nouveau_vieux_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/r200_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/r300_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/r600_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/radeon_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/zink_dri.so
      - -usr/lib/x86_64-linux-gnu/libLLVM-12.so.1
      - -usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0
      - -usr/share/doc/libdrm-common/changelog.Debian.gz
      - -usr/share/doc/libdrm2/changelog.Debian.gz
      - -usr/share/doc/libgbm1/changelog.Debian.gz
      - -usr/share/doc/libglapi-mesa/changelog.Debian.gz
      - -usr/share/doc/libllvm12/changelog.Debian.gz
      - -usr/share/doc/libtiff5/changelog.Debian.gz

  pulseaudio-common:
    source: bin
    plugin: dump
    organize:
      client-wrapper: bin/client-wrapper
      config: bin/config
      pulseaudio: bin/pulseaudio

  alsa-lib:
    plugin: autotools
    source: https://github.com/alsa-project/alsa-lib.git
    source-tag: v1.2.5.1
    prime:
      - -usr/include
      - -usr/share/aclocal
      - -usr/lib/lib*.la
      - -usr/lib/pkgconfig

  pulseaudio:
    plugin: meson
    source: https://github.com/pulseaudio/pulseaudio.git
    source-tag: v15.0
    source-depth: 1
    after: [ alsa-lib ]
    build-packages:
      - check
      - doxygen
      - intltool
      - libapparmor-dev
      - libdbus-1-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libspeexdsp-dev
      - libbluetooth-dev
      - libltdl-dev
      - libsndfile1-dev
      - libtdb-dev
      - libudev-dev
      - libasyncns-dev
      - libsbc-dev
      - libsnapd-glib-dev
      - libsoxr-dev
    stage-packages:
      - libapparmor1
      - libasyncns0
      - libbluetooth3
      - libflac8
      - libglib2.0-0
      - libgomp1
      - libjson-c4
      - libltdl7
      - libogg0
      - libsbc1
      - libsnapd-glib1
      - libsndfile1
      - libsoxr0
      - libsoxr-lsr0
      - libspeexdsp1
      - libtdb1
      - libudev1
      - libvorbis0a
      - libvorbisenc2
    meson-parameters:
      - --prefix="/usr"
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - -Dgstreamer="disabled"
      - -Dbluez5-gstreamer="disabled"
      - -Dorc="disabled"
      - -Dgsettings="disabled"
      - -Dadrian-aec="false"
      - -Dgtk="disabled"
      - -Dhal-compat="false"
      - -Dwebrtc-aec="disabled"
      - -Doss-output="disabled"
      - -Djack="disabled"
      - -Dx11="disabled"
      - -Dsystem_user="root"
      - -Dsystem_group="root"
      - -Daccess_group="root"
    override-build: |
      snapcraftctl build
      VER=$(cd $SNAPCRAFT_PART_SRC; git tag|sed 's/^v//')
      snapcraftctl set-version $VER
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
    override-prime: |
      snapcraftctl prime
      find usr/share/doc/ -type f,l ! -name copyright | xargs rm -rf
    prime:
      - -usr/include
      - -usr/share/zsh
      - -usr/share/bash-completion
      - -usr/share/man
      - -usr/share/GConf
      - -usr/share/lintian
      - -usr/share/vala
      - -usr/libexec
      - -usr/lib/cmake
      - -usr/lib/pkgconfig
      - -usr/lib/systemd
      - -etc/dconf

  alsa-plugins:
    plugin: autotools
    source: https://github.com/alsa-project/alsa-plugins.git
    source-tag: v1.2.5
    after: [ pulseaudio, alsa-lib ]
    autotools-configure-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc
    prime:
      - -usr/lib/alsa-lib/*.la

    stage:
      - -etc/alsa/conf.d/10-speexrate.conf
      - -etc/alsa/conf.d/50-arcam-av-ctl.conf
      - -etc/alsa/conf.d/50-oss.conf
      - -etc/alsa/conf.d/50-pulseaudio.conf
      - -etc/alsa/conf.d/60-upmix.conf
      - -etc/alsa/conf.d/60-vdownmix.conf
      - -etc/alsa/conf.d/98-usb-stream.conf

  alsa-ucm:
    plugin: dump
    source: https://github.com/alsa-project/alsa-ucm-conf.git
    source-tag: v1.2.5.1
    after: [ alsa-plugins ]
    organize:
      ucm: usr/share/alsa/ucm
      ucm2: usr/share/alsa/ucm2
    prime:
      - -README.md

environment:
  LD_LIBRARY_PATH: "$SNAP/usr/lib/pulseaudio:$SNAP/usr/lib/alsa-lib"
  PULSE_RUNTIME_PATH: /var/run/pulse
  PULSE_STATE_PATH: $SNAP_COMMON/state
  ALSA_CONFIG_UCM: $SNAP/usr/share/alsa/ucm2
  ALSA_CONFIG_TPLG: $SNAP/usr/share/alsa/topology
  ALSA_CONFIG_PATH: $SNAP/usr/share/alsa/alsa.conf
  ALSA_MIXER_SIMPLE: $SNAP/usr/share/alsa/smixer.conf
  ALSA_PLUGIN_DIR: $SNAP/usr/lib/alsa-lib


layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/local/share/fonts:
    bind: $SNAP/usr/local/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/pulse:
    bind: $SNAP/etc/pulse
  /etc/alsa:
    bind: $SNAP/etc/alsa
  /var/lib/pulse:
    bind: $SNAP_DATA
  /usr/lib/pulse-15.0:
    symlink: $SNAP/usr/lib/pulse-15.0
  /usr/lib/alsa-lib:
    bind: $SNAP/usr/lib/alsa-lib
  /usr/share/pulseaudio:
    symlink: $SNAP/usr/share/pulseaudio
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
  /usr/share/applications:
    bind: $SNAP/usr/share/applications

