name: cluemaster-mediadisplay
base: core20
version: '1.0.18'
summary: Clumaster.io Media Display for Escape Rooms
description: |
  ClueMaster Media Display is a Dynamic TV Display software for escape rooms.
  It shows escape room countdown timers, visual text messages, video, audio,
  and photo clues.
   
grade: stable 
confinement: strict

apps:
  cluemaster-mediadisplay:
    command: bin/desktop-launch prepare-launch $SNAP/cluemaster_display
    desktop: usr/share/applications/cluemaster-mediadisplay.desktop
    autostart: cluemaster-mediadisplay.desktop
    plugs:
      - home
      - desktop-legacy
      - desktop
      - wayland
      - x11
      - unity7
      - network
      - opengl
      - gsettings
      - pulseaudio
      - network-bind
      - screen-inhibit-control
      - audio-playback
      - shutdown
      - process-control
      - mount-observe
      - network-control

parts:
  copy-source-code:
    plugin: dump
    source: cluemaster_display/
    stage-packages:
      - ffmpeg
      - locales
      - libmpv1
      - va-driver-all
      - vdpau-driver-all
      - mesa-va-drivers
      - libvdpau-va-gl1
      - libglu1-mesa
      - samba-libs
      - git
      - python3-dbus
      - qtwayland5
      - python3-pyqt5.qtsvg
      - python3-pyqt5.qtmultimedia
      - python3
    
    stage:
      - -usr/lib/x86_64-linux-gnu/libLLVM-12.so.1
      - -usr/share/doc/libllvm12/changelog.Debian.gz


  desktop-files-and-icons:
    plugin: dump
    source: snap/gui/
    organize: 
      "cluemaster-mediadisplay.desktop": "usr/share/applications/"
      "cluemaster-mediadisplay.png": "usr/share/applications/"
    stage:
      - usr/share/applications/cluemaster-mediadisplay.desktop
      - usr/share/applications/cluemaster-mediadisplay.png

  extras:
    plugin: dump
    source: static/
    organize: 
      "prepare-launch": "bin/"

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try: [appmenu-qt5]
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

layout:
  /usr/share/libdrm/amdgpu.ids:
    symlink: $SNAP/usr/share/libdrm/amdgpu.ids
