#!/bin/sh

echo "Prepairing launch ..."

if [ ! -d "$SNAP_USER_DATA/.config/autostart" ];
then
  mkdir -p $SNAP_USER_DATA/.config/autostart
  ln -sfnt $SNAP_USER_DATA/.config/autostart/ $SNAP/meta/gui/cluemaster-mediadisplay.desktop
fi

exec "$@"
