#!/bin/sh

echo "Prepairing launch ..."
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$SNAP/usr/lib/x86_64-linux-gnu/samba":$LD_LIBRARY_PATH
export PYTHONPATH="$SNAP/usr/lib/python3/dist-packages"
echo "Environment variables setup complete ..."

if [ ! -d "$SNAP_USER_DATA/.config/autostart" ];
then
  mkdir -p $SNAP_USER_DATA/.config/autostart
  ln -sfnt $SNAP_USER_DATA/.config/autostart/ $SNAP/usr/share/applications/cluemaster-mediadisplay.desktop
fi

exec "$@"