name: cluemaster-mediadisplay-core
version: '2024.10.22-DEVELOPMENT'
summary: Clumaster.io TV Timer Display for Escape Rooms
description: |
  ClueMaster Media Display is a Dynamic TV Display software for escape rooms.
  It shows escape room countdown timers, visual text messages, video, audio,
  and photo clues. It also has the ability to remotely reboot and shutdown.


base: core24  # For Ubuntu Core 24 compatibility
grade: stable
confinement: strict

apps:
  cluemaster:
    command: bin/launch-cluemaster
    daemon: simple
    plugs:
      - network  # For internet communication
      - audio-playback  # To allow audio playback using PulseAudio
      - pulseaudio  # For PulseAudio interaction
      - opengl  # For graphics rendering with Ubuntu Frame
      - wayland  # Wayland support for Ubuntu Frame
      - ubuntu-frame  # Connect to Ubuntu Frame for video output
    environment:
      WAYLAND_DISPLAY: wayland-0  # Ensures Wayland is used for display
      PULSE_SERVER: unix:/run/user/1000/pulse/native  # PulseAudio setup

parts:
  cluemaster:
    plugin: python
    source: cluemaster_display_source
    override-build: |
      snapcraftctl build
      # Create a launcher script to start the Python application
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      echo "#!/bin/sh" > $SNAPCRAFT_PART_INSTALL/bin/launch-cluemaster
      echo "mpv --no-config --idle &" >> $SNAPCRAFT_PART_INSTALL/bin/launch-cluemaster
      echo "python3 $SNAP/cluemaster_display_source/main.py" >> $SNAPCRAFT_PART_INSTALL/bin/launch-cluemaster
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/launch-cluemaster

  mpv-dependencies:
    plugin: nil  # This part does not build anything but pulls stage-packages
    stage-packages:
      - mpv  # MPV for video playback
      - libmpv2  # Updated for CORE 24, MPV library
      - python3-mpv  # Python bindings for MPV
      - pulseaudio  # PulseAudio for audio
      - libglu1-mesa  # Add missing dependency for OpenGL
      - freeglut3-dev # Add missing dependency for libglut.so.3.12

plugs:
  audio-playback:
    interface: audio-playback

  pulseaudio:
    interface: pulseaudio

  opengl:
    interface: opengl

  wayland:
    interface: wayland

  ubuntu-frame:
    interface: content
    target: ubuntu-frame
    default-provider: ubuntu-frame
    content: ubuntu-frame
